### ISSUE TITLE
"Edit in emacs" doesn't work in "Firefox Developer Edition" browser

### ISSUE THREAD

**Issue by yqrashawn** [agzam/spacehammer#126]
works well in chrome, chrome canary and brave

when using in firefox dev edition, clipboard changed to the altered text after C-c C-c but it won't paste back

**Comment by agzam** [comment]
@yqrashawn  Could you toggle the hs.console, default binding is ``Cmd+Ctrl+` `` and post the relevant log?

**Comment by yqrashawn** [comment]
demo

**Comment by yqrashawn** [comment]
here is a video demonstrate it 
https://user-images.githubusercontent.com/15090582/133539017-08d201b3-e4ef-4545-b35f-196a62a071b2.mp4

**Comment by agzam** [comment]
@yqrashawn Feel free to re-open if it's still doesn't paste
