### ISSUE TITLE
regression: window undo appears to be broken

### ISSUE THREAD

**Issue by agzam** [agzam/spacehammer#127]
It looks like at some point `windows/undo` stopped working. Not a vital feature, but we probably should have a better strategy for deprecating existing functionality :)

A cursory glance did not show me any clues.

**Comment by eccentric-j** [comment]
What is the expected behavior?

**Comment by Grazfather** [comment]
Any chance you can find the culprit with `git bisect`?

**Comment by agzam** [comment]
So when you move/maximize/center window, it pushes it into the history stack, then when you `undo`, it suppose to restore the window to the previous state. Right now, I'm seeing the message in the console:

```
** Warning:  bind.fnl: Could not invoke action windows:undo-action
```

**Comment by eccentric-j** [comment]
Thanks! That error means that if you have a binding like `windows:undo-action` in config.fnl, it can't find the corresponding function that the string refers to. 

Replace `windows:undo-action` with `windows:undo`, I'll make a PR to make the error message more clear and update the default config.

Did write some notes on a potential migration system in #122

**Comment by agzam** [comment]
Thank you @eccentric-j. It's both - embarrassing and heartwarming to find myself having to catch up with the new development. I can hardly keep up with you guys. You are awesome!
