### ISSUE TITLE
bad argument #1 to 'for iterator' (table expected, got nil)

### ISSUE THREAD

**Issue by xiaobing-huang** [agzam/spacehammer#145]
After start my computer, activate modal, got below error:
> 2021-10-27 09:42:39: 09:42:39   apps.fnl:     app is now: nil
2021-10-27 09:42:39:                          app is now: nil
2021-10-27 09:42:39: 09:42:39 ERROR:   LuaSkin: hs.application.watcher callback: ...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:265: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
	[C]: in function 'next'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:265: in function 'hs.fnutils.find'
	(...tail calls...)
	./lib/apps.fnl:65: in local 'tx_fn'
	./lib/statemachine.fnl:30: in function 'lib.statemachine.send'
	(...tail calls...)
2021-10-27 09:43:38:                          app is now: nil
2021-10-27 09:43:38:                          app is now: nil
2021-10-27 09:43:38:                          app is now: nil
2021-10-27 09:43:38: 09:43:38 ERROR:   LuaSkin: hs.application.watcher callback: ...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:265: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
	[C]: in function 'next'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:265: in function 'hs.fnutils.find'
	(...tail calls...)
	./lib/apps.fnl:65: in local 'tx_fn'
	./lib/statemachine.fnl:30: in function 'lib.statemachine.send'
	(...tail calls...)

the main modal won't appear, then open hammerspoon console, main modal appears.

**Comment by Grazfather** [comment]
Did you happen to see anything?

**Comment by xiaobing-huang** [comment]
> Did you happen to see anything?

sorry for late feedback, the error still occurs.
> 2021-11-06 07:53:17: 07:53:17 ERROR:   LuaSkin: hs.application.watcher callback: ...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:265: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
	[C]: in function 'next'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:265: in function 'hs.fnutils.find'
	(...tail calls...)
	./lib/apps.fnl:65: in local 'tx_fn'
	./lib/statemachine.fnl:29: in function 'lib.statemachine.send'
	(...tail calls...)
2021-11-06 07:53:44: 07:53:44   apps.fnl:     app is now: nil
2021-11-06 07:53:44:                          app is now: nil
2021-11-06 07:53:44: 07:53:44 ERROR:   LuaSkin: hs.application.watcher callback: ./lib/apps.fnl:154: table index is nil
stack traceback:
	./lib/apps.fnl:154: in local 'sub'
	./lib/statemachine.fnl:44: in function 'lib.statemachine.send'
	(...tail calls...)

**Comment by xiaobing-huang** [comment]
just pulled the latest changes, will see whether the same error still occur.

**Comment by Grazfather** [comment]
I have not merged this fix. You would have to manually apply the change I mention above to test the fix.

**Comment by xiaobing-huang** [comment]
applied the changes, will let you know whether it works.

**Comment by Grazfather** [comment]
Any luck?

**Comment by xiaobing-huang** [comment]
> Any luck?

this error seems caused by [line 189 in apps.fnl ](https://github.com/agzam/spacehammer/blob/259ed79f2e435a0f9a64b69c77acd000a33fbdb5/lib/apps.fnl#L189)

the variable **apps** is nil, if i change apps to **state.context.apps**, the error will be gone.

**Comment by Grazfather** [comment]
I pushed a PR to fix the second error, but note that it's not the same as your original error.

**Comment by Grazfather** [comment]
@eccentric-j did my fix above fix the error you were having? Note that that error is not the same as the one fixed in #153, which is here:

```fennel
2021-11-06 07:53:44: 07:53:44 ERROR: LuaSkin: hs.application.watcher callback: ./lib/apps.fnl:154: table index is nil
stack traceback:
./lib/apps.fnl:154: in local 'sub'
./lib/statemachine.fnl:44: in function 'lib.statemachine.send'
(...tail calls...)
```

**Comment by eccentric-j** [comment]
Just pulled, will let you know

**Comment by eccentric-j** [comment]
Haven't seen this since so I think it's fixed
