### ISSUE TITLE
Spacehammer.el causes to doom/emacs to "blink"

### ISSUE THREAD

**Issue by dianrob** [agzam/spacehammer#148]
having the spacehammer.el in my config I can take notes quickly yet at the same time my doom/emacs blinks, as in vanishes for a splits second, especially when I scroll my agenda (I am on MacOS). The same effect doesn't appear when I comment the spacehammer.el in my config. Anybody has an idea?

Other than that greatest addon ever btw, thank you very much :)

**Comment by agzam** [comment]
I'm a long-time Spacemacs user, but I just recently started setting up Doom. I have not incorporated Spacehammer into my Doom config just yet. I'm gonna need a good block of at least an hour of free time for that. Lately, I'm having difficulty enjoying such luxury, so that may take a while.

**Comment by dianrob** [comment]
It is absolutely not related to spacehammer. Sorry. 

Just found out it's the emacs version. First I thought removing the spacehammer.el fixed it but that was nonsense. 

Sorry again. 

Solution is here, I used emacs-plus: https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#on-macos

**Comment by Grazfather** [comment]
Thanks for coming back and sharing your solution nonetheless
