### ISSUE TITLE
Once updated to fennel 1.0, 'fennelview' missing.

### ISSUE THREAD

**Issue by Grazfather** [agzam/spacehammer#154]
According to the [repo](https://gitlab.com/technomancy/fennelview) it's part of fennel now.

We can remove it from _repl.fnl_. Looks like it was left there accidentally.

**Comment by Grazfather** [comment]
If we just release a version that sets the min version of fennel to 1.x we can remove this. That's my recommendation.

**Comment by agzam** [comment]
Do you think we should assert the version programmatically? The only way [I have found so far] to read the version, is by doing something like this: `(hs.execute "/usr/local/bin/fennel -v")`. But we can't be sure that fennel is installed at that path. And I couldn't find any way of finding the executable in the path; things like `(hs. execute "where fennel")`, etc., don't seem to work.

**Comment by Grazfather** [comment]
We can do this:
```
>> (. (require :fennel.utils) :version)
"1.1.0"
```
Though if we want to check it properly we have to parse it as a semantic version... lazily we can just make sure the first int is >= 1?

**Comment by Grazfather** [comment]
Done in da5dde7
