### ISSUE TITLE
feature request: add REPL

### ISSUE THREAD

**Issue by agzam** [agzam/spacehammer#16]
Add Fennel REPL that sends values to Hammerspoon's IPC

**Comment by agzam** [comment]
If anyone wants to try implementing it, can follow the conversation here: https://lists.sr.ht/~technomancy/fennel/%3Cm1v9yka216.fsf%40gmail.com%3E

**Comment by Grazfather** [comment]
This is done! #93

**Comment by agzam** [comment]
It would be nice at some point to add instructions how get to REPL driven workflow, how to start the REPL, and connect to it from the editor/IDE.
