### ISSUE TITLE
_coresetup.lua:662: module 'core' not found

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [agzam/spacehammer#160]
*** ERROR: ...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: module 'core' not found:
	no field package.preload['core']

**Comment by agzam** [comment]
Please provide the version numbers.
It doesn't seem to be reproducible on:

Fennel 1.0.0 on Lua 5.4 and Hammerspoon 0.9.93 (6148)

**Comment by factotvm** [comment]
I'm experiencing the same issue. I have it working on an old machine, but a new one won't load.

```shell
❯ fennel -v
Fennel 1.0.0 on Lua 5.4
```

```shell
❯ lua -v
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
```

**Hammerspoon**: Version 0.9.93 (6148)


This is on an M1 Mac with Homebrew (in `/opt/homebrew/`).

Error:

```
2022-01-21 09:13:29: *** ERROR: ...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: module 'fennel' not found:
```

**Comment by Grazfather** [comment]
In the hammerspoon console print out `package.path`. Can fennel be found in there? I actually reported a bug about this thing Hammerspoon/hammerspoon#3081 which was fixed.

Basically hammerspoon doesn't know to look in _/opt/homebrew_ until the above fix is released you can either explicitly set the LUA_PATH or add fennel to _/usr/local/lib/lua/5.4/_

**Comment by factotvm** [comment]
I tried the new Hammerspoon version, and it didn't work. I also updated `init.lua` to several different incantations that look something similar to:

```lua
package.path = package.path .. ";" .. "/opt/homebrew/Cellar/lua/5.4.3_1/?.lua;"
```

I know nothing about Lua or Fennel, sorry... I'm trying to look at the lines below for a hint.

**Comment by Grazfather** [comment]
did you use the version linked in the ticket, or the release? I am at work and cannot check my package.page at the moment, but shouldn't your path contain your luarocks dir?

**Comment by factotvm** [comment]
The pre-release version he linked to in the ticket.

**Comment by factotvm** [comment]
**Hammerspoon**: Version 0.9.93 (6172)

**Comment by factotvm** [comment]
Here is `package.path`


`/Users/me/.hammerspoon/?.lua;/Users/me/.hammerspoon/?/init.lua;/Users/me/.hammerspoon/Spoons/?.spoon/init.lua;/opt/homebrew/share/lua/5.4/?.lua;/opt/homebrew/share/lua/5.4/?/init.lua;/opt/homebrew/lib/lua/5.4/?.lua;/opt/homebrew/lib/lua/5.4/?/init.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/Applications/Hammerspoon.app/Contents/Resources/extensions/?.lua;/Applications/Hammerspoon.app/Contents/Resources/extensions/?/init.lua;/opt/homebrew/Cellar/lua/5.4.3_1/?.lua;;/Users/me/.luarocks/share/lua/5.4/?.lua;/Users/me/.luarocks/share/lua/5.4/?/init.lua;/Users/me/.luarocks/share/lua/5.3/?.lua;/Users/me/.luarocks/share/lua/5.3/?/init.lua`

You can see both... (mine is the Cellar one). Have I don't something else? On the command line, everything seems fine.

**Comment by Grazfather** [comment]
Happy to hear!
