### ISSUE TITLE
my hotkey wont work, when i use the hotkey in the console my counter wont go up

### ISSUE THREAD

**Issue by Bleupoliwag** [agzam/spacehammer#166]

**Comment by agzam** [comment]
It's difficult to guess what's not working without additional context. Please provide some if you still need help.

**Comment by Bleupoliwag** [comment]
[C]: in function 'assert'
	/Users/jennifertarver/.hammerspoon/init.lua:4: in function </Users/jennifertarver/.hammerspoon/init.lua:1>
2022-06-21 23:41:08: 23:41:08 ERROR:   LuaSkin: hs.hotkey callback: /Users/jennifertarver/.hammerspoon/init.lua:4: [////Users/jennifertarver/Desktop/shiny-counter.txt]: No such file or directory


what am i doing wrong? i followed the script and put it in as it should be, and it says the hot key is enabled, but when i put it in? it wont work and says theres an error?

**Comment by Bleupoliwag** [comment]
ive also moved my text document and put the document location as the pathway and it still wont work
