### ISSUE TITLE
Typo in init.lua file?

### ISSUE THREAD

**Issue by futuro** [agzam/spacehammer#19]
While exploring this repo, I was reading the `init.lua` file and came across what seemed like a typo, so I figured I'd open an issue just in case.

Is `package.loadeers` supposed to be `package.loaders`? See [line 4 of init.lua](https://github.com/agzam/spacehammer/blob/5dc11cde1ff7ed8a79019a1a485e24be0bef3f67/init.lua#L4)

Sorry if this is noise.

**Comment by agzam** [comment]
Oh, shoot... it is indeed a typo. Thank you so much for reporting this. I honestly have no idea how this still been working. ;)

**Comment by agzam** [comment]
fixed in https://github.com/agzam/spacehammer/commit/e2500d45e114078eb39eecead94e1cbc09a8f446
