### ISSUE TITLE
Tab switcher and local keys get deactivated sometimes

### ISSUE THREAD

**Issue by agzam** [agzam/spacehammer#31]
Sometimes Tab-switcher `CMD+j/k` for browser apps, gets deactivated seemingly for no apparent reason. Not sure what's causing it. For now the only workaround is to reload the Hammerspoon config.

upd: it seems App local keybindings, e.g. Slack specific keybindings stop working as well.

**Comment by eccentric-j** [comment]
Based on some additional logging it seems the hs.application.watcher instance itself stops working. Looking at hammerspoon's issues a very similar issue was reported:

https://github.com/Hammerspoon/hammerspoon/issues/681

Seems like people were able to resolve it by assigning the application watcher instance to a global variable and making sure another function references it somewhere so it doesn't get garbage collected.

Not 100% certain this will fix it, but I will give it a shot.
