### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by eggcaker** [agzam/spacehammer#4]
I'm not sure is the spacehammer bug on my mac  or I just did totally wrong. I downloaded the latest version of Hammerspoon ( 0.9.52 ), then clone this repo. after restart os,  when I press CMD SPC nothing happened.  Did i missing some thing?

**Comment by willmcclellan** [comment]
Same here. I could get it working by switching to ctrl instead of cmd.

I unmapped and existing settings in keyboard preferences and there's no logs, it just doesn't trigger.

**Comment by agzam** [comment]
Explained here: https://github.com/agzam/spacehammer#important-note
