### ISSUE TITLE
:exit function doesn't execute all the time

### ISSUE THREAD

**Issue by agzam** [agzam/spacehammer#42]
`:exit` function of a modal seems to be firing only when explicitly exiting modal. e.g.:

    (local menu-items
      {:key   :w
       :title "Window"
       :enter (fn [] (print "enter"))
       :exit  (fn [] (print "exit"))
       :items window-bindings}
       
When pressed `Alt+SPC w` - it prints "enter", when "Esc" - prints "exit". But if instead of pressing "Esc" (while in the modal) - you press "SPC" - it would go back to previous modal, but won't fire `:exit` handler, and it should.

**Comment by eccentric-j** [comment]
```fennel
(local window-items
       (concat
        [return
         {:key :w
          :title "Last Window"
          :action "windows:jump-to-last-window"}]
        window-layouts
        window-jumps
        window-move-screens
        [{:key :m
          :title "Maximize"
          :action "windows:maximize-window-frame"}
         {:key :c
          :title "Center"
          :action "windows:center-window-frame"}
         {:key :g
          :title "Grid"
          :action "windows:show-grid"}
         {:key :u
          :title "Undo"
          :action "windows:undo-action"}
         {:key :s
          :title "Test Section"
          :enter (fn [] (print "Enter test section"))
          :exit (fn [] (print "Exit test section"))
          :items [return
                  {:key :s
                   :title "Test section item"
                   :action (fn [] nil)}]}]))
```

That's what I have in my config.fnl.

I then did the following:
1. Pressed `CMD+SPACE w`
2. Pressed `s`
3. Looked at the log, saw "Enter test section"
4. Pressed `<space>`
5. Looked at the log, saw "Exit test section"
6. Pressed `CMD+SPACE w s` again
7. Looked at the log, saw "Enter test section" again
8. Pressed `<escape>`
9. Looked at the log, saw "Exit test section" again

What is in your config?

**Comment by agzam** [comment]
Ah, I might've reported this prematurely. I'll check again. My apologies for having you to waste your time. Thank you for checking this so quickly.
