### ISSUE TITLE
edit-with-emacs: selection

### ISSUE THREAD

**Issue by agzam** [agzam/spacehammer#55]
Edit-with-Emacs future could be improved further. It would be nice to be able to detect if there's a selection already, instead of emulating "Select all" all the time. That would allow editing a pre-selected chunk of text. I don't know if there's a "proper" way of detecting if there's a selection. Perhaps we can read the clipboard, copy, compare currently copied with the previous thing, and somehow decide if it has to be done with Cmd+A and Cmd+C, or doing Cmd+C (without selecting all) is enough.

**Comment by eccentric-j** [comment]
I've been using:

```
(fn selected-text
  []
  (when-let [el (hs.uielement.focusedElement)]
    (: el :selectedText)))
```

I've been using that in my plugin to send arbitrary code to a tmux session. It works ok but when using it with emacs there are times the wrong text is returned or it returns the previous selection\region.

Is there a CLI we can shell out to that can read selections better from OS X? Or maybe we can fake it by running cmd c, then examining the pasteboard to see if anything has been copied. If it does that means text was selected right?

**Comment by agzam** [comment]
I've tried it, and somehow hs.uielement doesn't work in browsers (except Safari). I've reported an issue https://github.com/Hammerspoon/hammerspoon/issues/2362, let's see, maybe someone suggests a workaround.

**Comment by eccentric-j** [comment]
Oh right! Sorry, I forgot to mention it doesn't work in most browsers and electron apps like Slack, Atom or VS Code.

That said, what about running cmd-c then examining the pasteboard? If it changed, there's a selection and we can use that. If it doesn't change, then we should invoke cmd-a first then cmd-c again.

```elisp
(let [prev (hs.pasteboard.getContents)]
  (hs.pasteboard.setÇontents "")
  (hs.eventtap.keyStroke [:cmd] :c)
  (let [next (hs.pasteboard.getContents)]
    (hs.pasteboard.setContents prev)
    (if (= prev next)
      (println "Pasteboard was updated so text was selected")
      (println "Pasteboard was not updated so no text was selected"))))
```

**Comment by eccentric-j** [comment]
Oh! Actually a better way might be to use the changeCount function:

```elisp
(let [prev (hs.pasteboard.changeCount)]
  (hs.eventtap.keyStroke [:cmd] :c)
  (let [next (hs.pasteboard.changeCount)]
    (if (= prev next)
      (println "Pasteboard was not updated so no text was selected")
      (println "Pasteboard was updated so text was selected"))))
```

**Comment by agzam** [comment]
I'll try that out, thanks @eccentric-j
