### ISSUE TITLE
Error Message on window management menu

### ISSUE THREAD

**Issue by jonathanabennett** [agzam/spacehammer#57]
I have installed spacehammer according to the instructions in the readme. The only changes I have made to my system were to modify line 349 of ~/.spacehammer/config.fnl to so that CMD+Space is the LEAD and to load spacehammer.el in my init.el file.

To reproduce: Focus a window and press LEAD + w
Expected Result: The window prompt appears
Actual result: The following is output to the Hammerspoon console and the Spacehammer overlay freezes until you focus the Hammerspoon app and press escape.

`2020-05-13 22:16:37: 22:16:37 ERROR:   LuaSkin: hs.hotkey callback: ./lib/functional.fnl:43: bad argument #1 to 'concat' (table expected, got nil)
stack traceback:
	[C]: in function 'table.concat'
	./lib/functional.fnl:43: in function 'lib.functional.join'
	./lib/modal.fnl:107: in upvalue 'format_key'
	./lib/modal.fnl:127: in upvalue 'f'
	./lib/functional.fnl:137: in local 'f'
	./lib/functional.fnl:117: in function 'lib.functional.reduce'
	(...tail calls...)
	./lib/modal.fnl:132: in upvalue 'modal_alert'
	./lib/modal.fnl:148: in upvalue 'show_modal_menu'
	./lib/modal.fnl:229: in function <./lib/modal.fnl:215>
	(...tail calls...)
	./lib/statemachine.fnl:65: in function <./lib/statemachine.fnl:47>
	(...tail calls...)`

I'm brand new to Hammerspoon, so I suspect this is user error, but I do not see a Spacehammer community to ask this question in so I'm raising it as an issue.

**Comment by eccentric-j** [comment]
Can you please share your ~/.spacehammer/config.fnl?

**Comment by agzam** [comment]
It's due to Fennel 0.4.0 changes.

**Comment by agzam** [comment]
luarocks install fennel 0.3.2

**Comment by agzam** [comment]
@eccentric-j the problem seems to be here: https://github.com/agzam/spacehammer/blob/master/lib/modal.fnl#L231
, but I don't remember now, what's happening here, what are `item.mods` for?

**Comment by eccentric-j** [comment]
That's for translating the mods in a menu item like:

```
{:title "Do the thing"
 :key :q
 :mods [:cmd]
 :action "my-module:do-the-thing"}
```

So when it's displayed in the modal it reads:
 ```CMD + q               do the thing```

It's not much now but I was experimenting with displaying it like `⌘ + q
         do the thing`, I left it so if there were any cases where we
wanted to change how a mod was displayed there was an easy entry point for
it.

That said what would cause it to break now? I'll check the fennel 0.4.0
changelog and see if anything sticks out. Thanks for drilling down into it.

Best,
Jay

**Comment by eccentric-j** [comment]
That's for translating the mods in a menu item like:

```
{:title "Do the thing"
 :key :q
 :mods [:cmd]
 :action "my-module:do-the-thing"}
```

So when it's displayed in the modal it reads:
```
CMD + q               do the thing
```

It's not much now but I was experimenting with displaying it like 
`⌘ + q              do the thing`, I left it so if there were any cases where we
wanted to change how a mod was displayed there was an easy entry point for
it.

That said what would cause it to break now? I'll check the fennel 0.4.0
changelog and see if anything sticks out. Thanks for drilling down into it.

**Comment by agzam** [comment]
Then I would leave it to you to fix it, I don't want to remove anything valuable. I'm not sure why it stopped working in Fennel  0.4.0, basically now `join` wants a table not a `nil` and since `item.mods` is nil `-?>>` threads nil into `join`.

**Comment by jonathanabennett** [comment]
Thank you! I'm rolling back to Fennel 0.3.2 for now.

**Comment by eccentric-j** [comment]
@agzam You're right! It seems like there may be a bug in the latest fennel around the -?>> macro.

For additional color, this only occurs when a menu item has the `mods` attribute set.

**Comment by eccentric-j** [comment]
Pinpointed the behavior and reported it upstream. I isolated it to the -?>> not properly handling the last form, the simple fix is to use something like identity last.

**Comment by eccentric-j** [comment]
The workaround is in place should be compatible with 0.4.0 now.

**Comment by cicerojones** [comment]
I'm still experiencing this problem. It appears that fennel has been updated yet again? 

I tried rolling back, but still had the problem described with modal.fnl. It's possible that I was doing something wrong, as I couldn't get it to work even 0.3.2

`nas-MacBook-Pro:~ na$ luarocks remove fennel
Checking stability of dependencies in the absence of
fennel 0.5.0-4...

Removing fennel 0.5.0-4...
Removal successful.
nas-MacBook-Pro:~ na$ luarocks install fennel 0.4.0
Installing https://luarocks.org/fennel-0.4.0-1.src.rock

fennel 0.4.0-1 depends on lua >= 5.1 (5.3-1 provided by VM)
fennel 0.4.0-1 is now installed in /usr/local (license: MIT)

$ luarocks remove fennel
Checking stability of dependencies in the absence of
fennel 0.4.0-1...

Removing fennel 0.4.0-1...
Removal successful.
$ luarocks install fennel 0.3.2
Installing https://luarocks.org/fennel-0.3.2-1.src.rock

fennel 0.3.2-1 depends on lua >= 5.1 (5.3-1 provided by VM)
fennel 0.3.2-1 is now installed in /usr/local (license: MIT)`

Please let me know if I can provide better info.

**Comment by eccentric-j** [comment]
Seems like it's running with the latest fennel (0.5). Can you please check the following:

```
 > lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
 > luarocks --version
/usr/local/bin/luarocks 3.3.1
 > fennel --version
Fennel 0.5.0 on Lua 5.3
```

If those are the same, can you try the following:

```
cd ~/.hammerspoon
git fetch origin master
git reset --hard origin/master
```

Then reload hammerspoon?

**Comment by eccentric-j** [comment]
After I tried that myself, I ran into an issue. Please hold while I investigate this.

**Comment by eccentric-j** [comment]
@jonathanabennett When I tried those steps, I used the wrong remote due to my personal config but the commands above will work. Please try them when you get the chance and let us know if the cause is still unclear. I want to get to the bottom of this!

**Comment by agzam** [comment]
I've been running things for a while on `Fennel 0.5.0` (haven't seen any problems), but I haven't updated to `0.5.0-4`, I will try.

**Comment by cicerojones** [comment]
Well, I think I've done what's outlined here (and I will share those results to just confirm), but thought I'd just post what looks to be a suspiciously silly error that appears on reload of the hammerspoon config:

```
2020-08-20 20:45:42: -- Lazy extension loading enabled
2020-08-20 20:45:42: -- Loading ~/.hammerspoon/init.lua
2020-08-20 20:45:42: -- Loading extension: alert
2020-08-20 20:45:43: *** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: module 'core' not found:
	no field package.preload['core']
	no file '/Users/na/.hammerspoon/core.lua'
	no file '/Users/na/.hammerspoon/core/init.lua'
	no file '/Users/na/.hammerspoon/Spoons/core.spoon/init.lua'
	no file '/usr/local/share/lua/5.3/core.lua'
	no file '/usr/local/share/lua/5.3/core/init.lua'
	no file '/usr/local/lib/lua/5.3/core.lua'
	no file '/usr/local/lib/lua/5.3/core/init.lua'
	no file './core.lua'
	no file './core/init.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/core.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/core/init.lua'
	no file '/Users/na/.hammerspoon/core.so'
	no file '/usr/local/lib/lua/5.3/core.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './core.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/core.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/na/.hammerspoon/init.lua:19: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
```

There's something I'm not doing right if things like `core.lua` can't be found (because they don't exist, of course)?

**Comment by cicerojones** [comment]
This seems to be the relevant part of the console error message:
```
2020-08-20 21:06:25:          	modal.fnl:     state is now: idle
2020-08-20 21:06:25:                          {}
2020-08-20 21:06:25: ********
2020-08-20 21:06:25: 21:06:25 ERROR:   LuaSkin: hs.timer callback error: ./windows.fnl:19: attempt to index a nil value (local 'win')
stack traceback:
	./windows.fnl:19: in method 'push'
	./windows.fnl:65: in function 'windows.maximize-window-frame'
	(...tail calls...)
2020-08-20 21:06:25: ********
2020-08-20 21:06:28: 21:06:28 ** Warning:	statemach: Could not disable from disabled state
```

NB, all I'm trying to do primarily is just move and resize the my windows (via usual `lead W` commands), as well as, say, jump among `lead J` between various application windows. What's interesting is that these functions do work IF you are "lead W m" maximizing _the Hammerspoon_ console application window! Hmm.

**Comment by agzam** [comment]
> Sorry for muddling the thread!

No worries. We're glad you get it working.
