### ISSUE TITLE
Setting hyper to mods doesn't work

### ISSUE THREAD

**Issue by valrus** [agzam/spacehammer#63]
The docs contain an [example](https://github.com/agzam/spacehammer#global-keys) of binding the hyper key as a combination of modifiers:

```
{:hyper {:mods [:cmd :ctrl :alt :shift]}
```

However, when I try to do this in my own config, I get an error:

```
2020-06-08 22:43:59: *** ERROR: ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:408: key must be a string or a number
stack traceback:
	[C]: in function 'error'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:20: in upvalue 'getKeycode'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:195: in function 'hs.hotkey.new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:408: in function 'hs.hotkey.bind'
	(...tail calls...)
	./core.fnl:98: in upvalue 'f'
	./lib/functional.fnl:144: in local 'f'
	./lib/functional.fnl:124: in function 'lib.functional.reduce'
	(...tail calls...)
	./core.fnl:100: in main chunk
	(...tail calls...)
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/valrus/.hammerspoon/init.lua:19: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
```

I'm not sure as I don't really know Fennel, but it looks like `hyper.fnl` requires the `:hyper` table to have a `:key` (in `init`).

**Comment by eccentric-j** [comment]
Oh! That's unfortunate, you're partially right though. Hammerspoon requires a key to be bound, at least with the simpler [hs.hotkey](https://www.hammerspoon.org/docs/hs.hotkey.html) API. 

The setup I'm using for hyper uses [Karabiner Elements](https://karabiner-elements.pqrs.org/). I bind Caps Lock to a virtual key, F18 then set hyper to `{:key :F17}`.

Now I've got the whole keyboard at my disposal for custom, non-conflicting bindings. Though admittedly, it's not a great solution seeing as it involves another automation app.

More experimentation is required, but I believe the desired effect can be achieved using Hammerspoon's [hs.eventtap](https://www.hammerspoon.org/docs/hs.eventtap.html) module, it will involve a bit of state to make sure all the keys are pressed at the same time.

I will schedule some time within the next two weeks to experiment. Feel free to give it a shot and make a PR if it's more urgent for you.

**Comment by valrus** [comment]
Thanks for the detailed answer. For now it's working for me just to use

```
(local hyper
       [:alt :shift :ctrl :cmd])
```

with `:mods hyper` where necessary.
