### ISSUE TITLE
[BUG] Spacehammer can't find fennel.lua after updating to Hammerspoon 0.9.79

### ISSUE THREAD

**Issue by eccentric-j** [agzam/spacehammer#68]
# Reproduction
1. Install the latest Hammerspoon application
2. Restart Hammerspoon (close the app, or restart via auto-update)

## Expected
Hammerspoon should continue to work

## Actual
Hammerspoon breaks, will not load Spacehammer, and displays an error

```
2020-09-20 12:15:28: -- Lazy extension loading enabled
2020-09-20 12:15:28: -- Loading ~/.hammerspoon/init.lua
2020-09-20 12:15:28: -- Loading extension: alert
2020-09-20 12:15:28: *** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: module 'fennel' not found:
	no field package.preload['fennel']
	no file '/Users/davelu/.hammerspoon/fennel.lua'
	no file '/Users/davelu/.hammerspoon/fennel/init.lua'
	no file '/Users/davelu/.hammerspoon/Spoons/fennel.spoon/init.lua'
	no file '/usr/local/share/lua/5.4/fennel.lua'
	no file '/usr/local/share/lua/5.4/fennel/init.lua'
	no file '/usr/local/lib/lua/5.4/fennel.lua'
	no file '/usr/local/lib/lua/5.4/fennel/init.lua'
	no file './fennel.lua'
	no file './fennel/init.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/fennel.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/fennel/init.lua'
	no file '/Users/davelu/.hammerspoon/fennel.so'
	no file '/usr/local/lib/lua/5.4/fennel.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './fennel.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/fennel.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: in function 'require'
	/Users/davelu/.hammerspoon/init.lua:16: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
	(...tail calls...)
```

Thanks to @tntmarket for reporting this issue in https://github.com/agzam/spacehammer/issues/67.

**Comment by eccentric-j** [comment]
A fix is being worked on, ETA 30 minutes.

**Comment by eccentric-j** [comment]
Fix is complete. Awaiting code review and merge, and instructions are on agzam/spacehammer#70.

@agzam Could you give that a quick review as soon as you are able?

**Comment by eccentric-j** [comment]
https://github.com/Hammerspoon/hammerspoon/issues/2480 for tracking purposes

**Comment by x61** [comment]
Has this issue been resolved? I am having the same issue with the latest build. 
`2020-10-25 16:10:26: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2020-10-25 16:10:26: -- Lazy extension loading enabled
2020-10-25 16:10:26: -- Loading ~/.hammerspoon/init.lua
2020-10-25 16:10:26: *** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: module 'fennel' not found:
	no field package.preload['fennel']
	no file '/Users/h/.hammerspoon/fennel.lua'
	no file '/Users/h/.hammerspoon/fennel/init.lua'
	no file '/Users/h/.hammerspoon/Spoons/fennel.spoon/init.lua'
	no file '/usr/local/share/lua/5.4/fennel.lua'
	no file '/usr/local/share/lua/5.4/fennel/init.lua'
	no file '/usr/local/lib/lua/5.4/fennel.lua'
	no file '/usr/local/lib/lua/5.4/fennel/init.lua'
	no file './fennel.lua'
	no file './fennel/init.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/fennel.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/fennel/init.lua'
	no file '/Users/h/.luarocks/share/lua/5.4/fennel.lua'
	no file '/Users/h/.luarocks/share/lua/5.4/fennel/init.lua'
	no file '/Users/h/.luarocks/share/lua/5.3/fennel.lua'
	no file '/Users/h/.luarocks/share/lua/5.3/fennel/init.lua'
	no file '/Users/h/.hammerspoon/fennel.so'
	no file '/usr/local/lib/lua/5.4/fennel.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './fennel.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/fennel.so'
	no file '/Users/h/.luarocks/lib/lua/5.4/fennel.so'
	no file '/Users/h/.luarocks/lib/lua/5.3/fennel.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: in function 'require'
	/Users/h/.hammerspoon/init.lua:22: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
	(...tail calls...)`
Hammerspoon by itself works. I followed the instruction provided in #70 but still does not work

**Comment by AnikaSU** [comment]
I am having the same issue, too.

**Comment by eccentric-j** [comment]
@x61 https://github.com/Hammerspoon/hammerspoon/wiki/Luarocks-and-Hammerspoon

I am leaning towards the steps not being followed completely. You should be able to verify fennel by visiting the ~/.luarocks/share/lua/5.4/ directory:

```

jay at kamikaze-cabaret in ~
 > cd ~/.luarocks/share/lua/5.4/
jay at kamikaze-cabaret in ~/.l/s/l/5.4
 > ls -al
total 264
drwxr-xr-x  4 jay  staff     128 Sep 20 17:12 ./
drwxr-xr-x  3 jay  staff      96 Sep 20 17:12 ../
-rw-r--r--  1 jay  staff  126646 Sep 20 17:12 fennel.lua
-rw-r--r--  1 jay  staff    6326 Sep 20 17:12 fennelview.lua

```
