### ISSUE TITLE
Suggestion: show modal on all displays not just one

### ISSUE THREAD

**Issue by PaulMorris** [agzam/spacehammer#74]
Given an open laptop connected to an external display (or several?), I found that the modal appeared only on the laptop's screen and not the external display.  I think it would be better if the modal appeared on all displays so you would always see it, no matter which screen you are looking at.

I have a small edit that does this, that's working for me locally, and I'd be glad to submit a pull request if there is interest.

(Also, many thanks for this wonderful project!  I am really enjoying the ways it is improving my time spent staring at screens and pushing buttons.)

**Comment by agzam** [comment]
Personally, I don't use more than two displays at the moment, but I'm sure a few people probably  would like this. Also, it seems we currently show the HUD only on the main screen (that's the default behavior of `hs.alert.show`), maybe we should have an option to make it appear on the active screen (where the mouse cursor is). Thank you for the idea and for the kind words.

**Comment by eccentric-j** [comment]
If feel this would be best tackled via #72 or as a config option as I had experimented with this prior to the refactor and found it was obtrusive when watching fullscreen videos on another screen while looking up a word definition in Alfred for instance. If you feel this would make a better default, then the advising system would at least allow me to make it work like the current behavior without having to replace the whole call chain.

**Comment by Grazfather** [comment]
Sample fix:

```fennel
;; Make alerts show on all screens
(import-macros {: defadvice} :lib.advice.macros)
(defadvice alert-all
        [str style seconds]
        :override alert
        "Replace core.alert with one that alerts on all screens"
        (each [_ screen (pairs  (hs.screen.allScreens))]
          (hs.alert.show str
                         (or style 1)
                         screen
                         seconds)))
```
