### ISSUE TITLE
emacs opens a new instance instead of focusing existing one

### ISSUE THREAD

**Issue by dangom** [agzam/spacehammer#82]
When activating Emacs, spacehammer opens a new instance instead of focusing on an existing one.
I'm using the default config and a vanilla emacs setup.

My emacs 28 was installed by building it with [build-emacs-for-macos](https://github.com/jimeh/build-emacs-for-macos), and symlinked to /Applications/Emacs.app.
I open emacs by running `emacs &!` on my zsh.

Is there anything suspicious in my setup that could lead to this issue?
I do have a server running and can connect to it via emacsclient.

Other potentially relevant info:
Hammerspoon latest (0.9.86)
spacehammer latest (81ca4e0)
MacOS Catalina 10.15.7

**Comment by agzam** [comment]
What does running `open -a Emacs` from the terminal do for you? Does it activate existing instance or opens a new one?

**Comment by dangom** [comment]
Yes, it opens a new one

**Comment by agzam** [comment]
In that case this is neither a Hammerspoon, nor a Spacehammer issue. This is OSX thing, perhaps check if the app is properly linked. Maybe try tweaking `ns-pop-up-frames` var.

**Comment by agzam** [comment]
@dangom, I'm going to close this for now.
