### ISSUE TITLE
Feature request: styling of the modal(s)

### ISSUE THREAD

**Issue by ihodes** [agzam/spacehammer#86]
It would be nice to be able to style the modals, including how text is displayed (e.g. cmd → ⌘).

**Comment by eccentric-j** [comment]
This would also be doable with the advising system proposed in #72. Sounds like I better get cracking on this 😅

**Comment by ihodes** [comment]
Sorry for the bombardment with all these feature requests! I am a big fan of spacehammer and am super impressed with what you've done.  also love fennel, as I'm a long-time Clojurer. I hope to get a contribution in, and might start familiarizing myself by getting deeper into my config to address #85 :)

**Comment by eccentric-j** [comment]
Excellent, a fellow Clojurist! Thanks for reporting the issues, and feature requests separately. We appreciate the community activity either way. The discussions https://github.com/agzam/spacehammer/discussions might be a good medium if you end up getting stuck somewhere.

**Comment by agzam** [comment]
> Sorry for the bombardment with all these feature requests! 

Oh no, please don't hesitate to share any ideas - good or bad, mediocre or exceptional. Remember, this project grew out of some hobby attempts to improve my own workflow. It is very opinionated, and I never thought it would be useful for anyone else.

It still suffers from many careless design decisions I made in the beginning. I've been using Spacehammer for a few years now, and I get used to it too much. In many aspects - "it just works for me." But that doesn't mean that either I or @eccentric-j  are not interested in improving it further. Please keep sharing the ideas, and tell us how we can do better.

**Comment by eccentric-j** [comment]
Now that #107 is merged, it should be trivial to make the formatting functions advisable so users can tweak it to their liking

**Comment by eccentric-j** [comment]
Here is an example:

```fennel

(defadvice red-alert
           [str style seconds]
           :before alert
           "Customize the modal UI to make the text color red"
           (pprint style) ;; See what the default style props are
           (tset style :textColor { :red 1 :alpha 1}))

```

You can drop that into your config.fnl and tweak the style object. More details can be found at https://www.hammerspoon.org/docs/hs.alert.html#defaultStyle. Feel free to reopen if this doesn't cut it.
