### ISSUE TITLE
Slack scroll-up and scroll-down are backwards

### ISSUE THREAD

**Issue by Grazfather** [agzam/spacehammer#97]
```lisp
(fn scroll-to-bottom
  []
  (windows.set-mouse-cursor-at :Slack)
  (hs.eventtap.scrollWheel [0 -20000] {}))
...
(fn scroll-up
  []
  (scroll-slack -3))

(fn scroll-down
  []
  (scroll-slack 3))
```
We can see here that `scroll-down` has a positive direction, while `scroll-to-bottom` is negative. Clearly these should have the same sign, and it seems that `scroll-to-bottom` works as expected.

**Comment by eccentric-j** [comment]
Fixed by #102
